In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('NY-House-Dataset.csv')

In [3]:
print(data.head())

                                         BROKERTITLE                TYPE  \
0        Brokered by Douglas Elliman  -111 Fifth Ave      Condo for sale
1                                Brokered by Serhant      Condo for sale
2                             Brokered by Sowae Corp      House for sale
3                                Brokered by COMPASS      Condo for sale
4  Brokered by Sotheby's International Realty - E...  Townhouse for sale

       PRICE  BEDS       BATH  PROPERTYSQFT  \
0     315000     2   2.000000        1400.0
1  195000000     7  10.000000       17545.0
2     260000     4   2.000000        2015.0
3      69000     3   1.000000         445.0
4   55000000     7   2.373861       14175.0

                                             ADDRESS                    STATE  \
0                               2 E 55th St Unit 803       New York, NY 10022
1  Central Park Tower Penthouse-217 W 57th New Yo...       New York, NY 10019
2                                   620 Sinclair Ave  Staten Island, NY 10312
3                            2 E 55th St Unit 908W33      Manhattan, NY 10022
4                                        5 E 64th St       New York, NY 10065

                                        MAIN_ADDRESS  \
0             2 E 55th St Unit 803New York, NY 10022
1  Central Park Tower Penthouse-217 W 57th New Yo...
2            620 Sinclair AveStaten Island, NY 10312
3         2 E 55th St Unit 908W33Manhattan, NY 10022
4                      5 E 64th StNew York, NY 10065

  ADMINISTRATIVE_AREA_LEVEL_2  LOCALITY      SUBLOCALITY       STREET_NAME  \
0             New York County  New York        Manhattan  East 55th Street
1               United States  New York  New York County          New York
2               United States  New York  Richmond County     Staten Island
3               United States  New York  New York County          New York
4               United States  New York  New York County          New York

          LONG_NAME                                  FORMATTED_ADDRESS  \
0   Regis Residence  Regis Residence, 2 E 55th St #803, New York, N...
1  West 57th Street             217 W 57th St, New York, NY 10019, USA
2   Sinclair Avenue     620 Sinclair Ave, Staten Island, NY 10312, USA
3  East 55th Street               2 E 55th St, New York, NY 10022, USA
4  East 64th Street               5 E 64th St, New York, NY 10065, USA

    LATITUDE  LONGITUDE
0  40.761255 -73.974483
1  40.766393 -73.980991
2  40.541805 -74.196109
3  40.761398 -73.974613
4  40.767224 -73.969856

In [5]:
print(data.dtypes)

BROKERTITLE                     object
TYPE                            object
PRICE                            int64
BEDS                             int64
BATH                           float64
PROPERTYSQFT                   float64
ADDRESS                         object
STATE                           object
MAIN_ADDRESS                    object
ADMINISTRATIVE_AREA_LEVEL_2     object
LOCALITY                        object
SUBLOCALITY                     object
STREET_NAME                     object
LONG_NAME                       object
FORMATTED_ADDRESS               object
LATITUDE                       float64
LONGITUDE                      float64
dtype: object

In [6]:
# Get a summary of missing values in each column
print(data.isnull().sum())

BROKERTITLE                    0
TYPE                           0
PRICE                          0
BEDS                           0
BATH                           0
PROPERTYSQFT                   0
ADDRESS                        0
STATE                          0
MAIN_ADDRESS                   0
ADMINISTRATIVE_AREA_LEVEL_2    0
LOCALITY                       0
SUBLOCALITY                    0
STREET_NAME                    0
LONG_NAME                      0
FORMATTED_ADDRESS              0
LATITUDE                       0
LONGITUDE                      0
dtype: int64

Based on the summary, there are no missing values in each column

In [7]:
# Get a summary of descriptive statistics for numerical features
print(data.describe())

              PRICE         BEDS         BATH  PROPERTYSQFT     LATITUDE  \
count  4.801000e+03  4801.000000  4801.000000   4801.000000  4801.000000
mean   2.356940e+06     3.356801     2.373861   2184.207862    40.714227
std    3.135525e+07     2.602315     1.946962   2377.140894     0.087676
min    2.494000e+03     1.000000     0.000000    230.000000    40.499546
25%    4.990000e+05     2.000000     1.000000   1200.000000    40.639375
50%    8.250000e+05     3.000000     2.000000   2184.207862    40.726749
75%    1.495000e+06     4.000000     3.000000   2184.207862    40.771923
max    2.147484e+09    50.000000    50.000000  65535.000000    40.912729

         LONGITUDE
count  4801.000000
mean    -73.941601
std       0.101082
min     -74.253033
25%     -73.987143
50%     -73.949189
75%     -73.870638
max     -73.702450

In [8]:
# Check for duplicate rows
print(data.duplicated().sum())

214

In [9]:
# Remove duplicate rows
data.drop_duplicates(inplace=True)

In [10]:
# Create a new column for price per square foot
data['PRICE_PER_SQFT'] = data['PRICE'] / data['PROPERTYSQFT']

In [11]:
data

,BROKERTITLE,TYPE,PRICE,BEDS,BATH,PROPERTYSQFT,ADDRESS,STATE,MAIN_ADDRESS,ADMINISTRATIVE_AREA_LEVEL_2,LOCALITY,SUBLOCALITY,STREET_NAME,LONG_NAME,FORMATTED_ADDRESS,LATITUDE,LONGITUDE,PRICE_PER_SQFT
0,Brokered by Douglas Elliman -111 Fifth Ave,Condo for sale,315000,2,2.000000,1400.000000,2 E 55th St Unit 803,"New York, NY 10022","2 E 55th St Unit 803New York, NY 10022",New York County,New York,Manhattan,East 55th Street,Regis Residence,"Regis Residence, 2 E 55th St #803, New York, N...",40.761255,-73.974483,225.000000
1,Brokered by Serhant,Condo for sale,195000000,7,10.000000,17545.000000,Central Park Tower Penthouse-217 W 57th New Yo...,"New York, NY 10019",Central Park Tower Penthouse-217 W 57th New Yo...,United States,New York,New York County,New York,West 57th Street,"217 W 57th St, New York, NY 10019, USA",40.766393,-73.980991,11114.277572
2,Brokered by Sowae Corp,House for sale,260000,4,2.000000,2015.000000,620 Sinclair Ave,"Staten Island, NY 10312","620 Sinclair AveStaten Island, NY 10312",United States,New York,Richmond County,Staten Island,Sinclair Avenue,"620 Sinclair Ave, Staten Island, NY 10312, USA",40.541805,-74.196109,129.032258
3,Brokered by COMPASS,Condo for sale,69000,3,1.000000,445.000000,2 E 55th St Unit 908W33,"Manhattan, NY 10022","2 E 55th St Unit 908W33Manhattan, NY 10022",United States,New York,New York County,New York,East 55th Street,"2 E 55th St, New York, NY 10022, USA",40.761398,-73.974613,155.056180
4,Brokered by Sotheby's International Realty - E...,Townhouse for sale,55000000,7,2.373861,14175.000000,5 E 64th St,"New York, NY 10065","5 E 64th StNew York, NY 10065",United States,New York,New York County,New York,East 64th Street,"5 E 64th St, New York, NY 10065, USA",40.767224,-73.969856,3880.070547
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4796,Brokered by COMPASS,Co-op for sale,599000,1,1.000000,2184.207862,222 E 80th St Apt 3A,"Manhattan, NY 10075","222 E 80th St Apt 3AManhattan, NY 10075",New York,New York County,New York,Manhattan,222,"222 E 80th St #3a, New York, NY 10075, USA",40.774350,-73.955879,274.241298
4797,Brokered by Mjr Real Estate Llc,Co-op for sale,245000,1,1.000000,2184.207862,97-40 62 Dr Unit Lg,"Rego Park, NY 11374","97-40 62 Dr Unit LgRego Park, NY 11374",United States,New York,Queens County,Queens,62nd Drive,"97-40 62nd Dr, Rego Park, NY 11374, USA",40.732538,-73.860152,112.168812
4798,Brokered by Douglas Elliman - 575 Madison Ave,Co-op for sale,1275000,1,1.000000,2184.207862,427 W 21st St Unit Garden,"New York, NY 10011","427 W 21st St Unit GardenNew York, NY 10011",United States,New York,New York County,New York,West 21st Street,"427 W 21st St, New York, NY 10011, USA",40.745882,-74.003398,583.735652
4799,Brokered by E Realty International Corp,Condo for sale,598125,2,1.000000,655.000000,91-23 Corona Ave Unit 4G,"Elmhurst, NY 11373","91-23 Corona Ave Unit 4GElmhurst, NY 11373",New York,Queens County,Queens,Flushing,91-23,"91-23 Corona Ave. #4b, Flushing, NY 11373, USA",40.742770,-73.872752,913.167939
4800,Brokered by Nyc Realty Brokers Llc,Co-op for sale,349000,1,1.000000,750.000000,460 Neptune Ave Apt 14O,"Brooklyn, NY 11224","460 Neptune Ave Apt 14OBrooklyn, NY 11224",New York,Kings County,Brooklyn,Coney Island,460,"460 Neptune Ave #14a, Brooklyn, NY 11224, USA",40.579147,-73.970949,465.333333

In [12]:
# Save the cleaned data to a new CSV file
data.to_csv('cleaned_data.csv', index=False)